### ISSUE TITLE
CLI script unable to find org.autorefactor.cli.AutoRefactor

### ISSUE THREAD

**Issue by MarcoCouto** [cal101/AutoRefactor#1]
Maybe this isn't exactly an issue, but here it goes.
I ran the command to build the CLI, like stated in the README, and everything went well.
I then tried to run CLI, like this: `./cli/target/autorefactor/bin/autorefactor --help`, and I got the following error in the log file:
```
Application "org.autorefactor.cli.AutoRefactor" could not be found.
```

What am I missing here? I have AutoRefactor installed on eclipse (through the Marketplace). Why can't I run the CLI? Do I need to install something else?

**Comment by cal101** [comment]
Hi!

I am planning a major update ATM.
The cli won't work with standard autorefactor but includes it's own version. 
The necessary changes for external control are minor and I may try a pull request and total separation for later versions.
The repo version might work with eclipse up to neon only. Next version will target oxygen.
Stay tuned.

**Comment by MarcoCouto** [comment]
So, you're saying that if I use an older eclipse version than oxygen, without the AutoRefactor plugin installed, the CLI should work?

How long do you think it will take to release the oxygen compatible release?
Thanks!

**Comment by cal101** [comment]
Maybe. AFAIR i got it running with neon. But since the includedcautorefactor is old, too, i suggest waiting for the next version.
I am trying to get it online next weekend.

**Comment by cal101** [comment]
I updated the repository.
Please note that the name of the repository changed and the content was rebased and cleaned up.
Please do a fresh checkout and use './build-cli'.
Please let me know if that works for you.
I plan to make a kind of "binary" package then.

**Comment by MarcoCouto** [comment]
Hi!
It's still not working with `oxygen`. I tried using `neon` and I got the same error: 
```
Application "org.autorefactor.cli.AutoRefactor" could not be found.
```
Both eclipse versions are clean installs, without anything on them. What could be the problem?
I am using the code under the `master` branch. Should I use a different one?
Is it possible for you to provide your eclipse bundle _as it is_?

Thanks in advance!

**Comment by cal101** [comment]
I will prepare a binary version in the next days.

**Comment by MarcoCouto** [comment]
The thing is I wanted to use my own custom refactoring rules, along with the existing ones :)
With the binary, I can only use the already existing ones, right?

If this works fine with you, maybe your eclipse has something that mine doesn't.
The `build-cli` script is supposed to install `AutoRefactor` _as it is_ on eclipse, right? Is it possible that `build-cli` is missing something (like copy-&-paste a .jar, for instance), that you are not checking since your eclipse already has `AutoRefactoCli` installed?

**Comment by cal101** [comment]
I just did the following on my machine.

1. Download fresh eclipse
2. Clone and build cli
3. Run it

```
mkdir test-vanilla
cd test-vanilla
# download eclipse oxygen 3a
wget 'http://www.eclipse.org/downloads/download.php?file=/technology/epp/downloads/release/oxygen/3a/eclipse-jee-oxygen-3a-linux-gtk-x86_64.tar.gz&r=1'
mv download.php* eclipse-jee-oxygen-3a-linux-gtk-x86_64.tar.gz
tar zxf eclipse-jee-oxygen-3a-linux-gtk-x86_64.tar.gz

# short test that eclipse starts up (press cancel when asked for workspace)
eclipse/eclipse

# checkout autorefactor cli 
git clone git@github.com:cal101/AutoRefactorCli.git
cd AutoRefactorCli
./build-cli
AUTOREFACTOR_ECLIPSE=../eclipse/eclipse ./cli/target/autorefactor/bin/autorefactor --help
```

The output is the usage help for me.

**Comment by MarcoCouto** [comment]
Well, if I meticulously follow your steps, it works for me too...
Also, if I just replace my `oxygen` version with the downloaded version you pointed, it still works.
But if I use the version I got from [here](https://www.eclipse.org/downloads/download.php?file=/oomph/epp/oxygen/R2/eclipse-inst-linux64.tar.gz), it doesn't work.

Weird as it may be, it works now so I'm glad :) Thanks for all the help!

**Comment by cal101** [comment]
Nice to hear.
